### ISSUE TITLE
DVTCoreSimulatorAdditionsErrorDomain error 0

### ISSUE THREAD

**Issue by shishuo365** [fwartner/mac-cleanup#19]
在更新到XCode10后，执行完清理操作，会出现如下错误：
I get this error when build xcode 10 project, after run cleanup.sh command.

```
The operation couldn’t be completed. (DVTCoreSimulatorAdditionsErrorDomain error 0.)
```

修复方法：
I tried this command to resolve this issue.

```
xcrun simctl erase all
```

**Comment by fwartner** [comment]
English, please. Otherwise, I won't be able to help you.
