### ISSUE TITLE
'brew upgrade --cleanup' is disabled

### ISSUE THREAD

**Issue by leomikezee** [fwartner/mac-cleanup#20]
Got the following message:
`Error: Calling 'brew upgrade --cleanup' is disabled! There is no replacement.`

**Comment by fwartner** [comment]
Have you updated your homebrew installation?

**Comment by leomikezee** [comment]
Yes, I got the latest version of homebrew.

**Comment by fuzheng1998** [comment]
maybe there are [replacement](https://github.com/Homebrew/brew/issues/4466#issuecomment-405132298)

**Comment by benmarten** [comment]
I think it's equivalent to: `brew update && brew upgrade && brew cleanup`.
