### ISSUE TITLE
Would be nice to install using brew

### ISSUE THREAD

**Issue by nitrocode** [fwartner/mac-cleanup#31]
Something like this would be more convenient

    brew install cleanup
    brew install mac-cleanup

**Comment by fwartner** [comment]
Well that´s a great idea!

**Comment by shin-sforzando** [comment]
Has anyone started this issue?
I made a LGTM Formula, but it's the author's prerogative to push it to Homebrew.

```/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mac-cleanup.rb
class MacCleanup < Formula
  desc "Cleanup script for OSX"
  homepage "https://github.com/fwartner/mac-cleanup/"
  url "https://github.com/fwartner/mac-cleanup/archive/1.0.2.tar.gz"
  sha256 "52c454c9abac16801814a90d766ff1d7367a698b0e003bc3dfe02cdfde6d1fa6"

  def install
    chmod 0755, "cleanup.sh"
    bin.install "cleanup.sh" => "cleanup"
  end

  test do
    system "#{bin}/cleanup"
  end
end
```

<img width="960" alt="Screen Shot 2020-06-07 at 1 45 56" src="https://user-images.githubusercontent.com/32637762/83949821-d6113480-a860-11ea-9c0b-27bdf0e94e75.png">

I sincerely hope it's officially approved.

**Comment by nitrocode** [comment]
Nice job! Actually the homebrew community discourages repo owners from submitting formula for their own projects.

if you put in a pr for the formula above, there's a good chance that they will accept it and we can all benefit.

**Comment by shin-sforzando** [comment]
> Nice job! Actually the homebrew community discourages repo owners from submitting formula for their own projects.

O, really? Where is it written?
As you can see, my formula is referring to this branch's release URL. 
If @fwartner and core contributors doesn't do the same Release, it won't work. So I'd like to leave the PR to Homebrew to the author, if possible.

**Comment by fwartner** [comment]
Submitted the PR: [#55930](https://github.com/Homebrew/homebrew-core/pull/55930)

Thank you for your support! :)

**Comment by shin-sforzando** [comment]
My pleasure:)

**Comment by shin-sforzando** [comment]
@fwartner Thank you for adding MIT License.
I'm rooting for you!

**Comment by nitrocode** [comment]
> O, really? Where is it written?
> As you can see, my formula is referring to this branch's release URL.
> If @fwartner and core contributors doesn't do the same Release, it won't work. So I'd like to leave the PR to Homebrew to the author, if possible.

I was referring to this

> We frown on authors submitting their own work unless it is very popular.

From [Acceptable-Formulae#niche-or-self-submitted-stuff](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff) but I suppose it meets the criteria of "very popular" due to the star count.

**Comment by superfunkminister** [comment]
@fwartner https://github.com/Homebrew/homebrew-core/pull/55930#issuecomment-683808587 would you mind opening a new PR? Would be awesome to get this on Homebrew!

**Comment by fwartner** [comment]
Done :)
