### ISSUE TITLE
Option to avoid brew updates

### ISSUE THREAD

**Issue by kodaman2** [fwartner/mac-cleanup#34]
I think it would be a good choice to take a parameter to avoid updating brew updates.
Brew updates alone took nearly 15~min for me, which was not optimal but not entirely bad.

I can make PR is you like the idea, or is this needed to clean up brew junk files?

**Comment by fwartner** [comment]
Sure! Do a PR and I will look over it! :)

**Comment by kodaman2** [comment]
Added #35
