### ISSUE TITLE
Chrome profile deleted

### ISSUE THREAD

**Issue by jrodan** [fwartner/mac-cleanup#43]
Hi, 

after running the cleanup script, my google chrome profile was deleted completely. 
I have no logfiles or recieved any error message.
Any support possible?
Thanks!

**Comment by fwartner** [comment]
Hey! I fixed it.. Should work now as expected! :)

**Comment by jrodan** [comment]
thanks!
Maybe some automated tests would be helpful?!
I crashed my chrome and was just lucky that I had the account sync activated ;)

**Comment by fwartner** [comment]
I am so sorry to hear that.. There are plans to rewrite the code soon.. Also with tests.
