### ISSUE TITLE
cleanup more cache data 

### ISSUE THREAD

**Issue by jrodan** [fwartner/mac-cleanup#44]
Hi, 
when I am using CleanMyMac X, the tool is providing me some more features of cleaning up temp/cache files:
![Bildschirmfoto 2020-08-27 um 15 08 22](https://user-images.githubusercontent.com/6048704/91445998-294ebe00-e877-11ea-90ca-091c11e17651.png)
![Bildschirmfoto 2020-08-27 um 15 08 45](https://user-images.githubusercontent.com/6048704/91446041-37044380-e877-11ea-835b-438461985c12.png)
please add some more cache remove lines for the most important apps like intellij, Spotify, ...

Thanks!

**Comment by fwartner** [comment]
Sure..! Any PR will be welcomed!

**Comment by Gummibeer** [comment]
@jrodan several of the listed parts should be cleared now.
Purging language files isn't really recommended as you manipulate all installed apps.
