### ISSUE TITLE
Negative number in clean up results

### ISSUE THREAD

**Issue by luutruong** [fwartner/mac-cleanup#66]
`-18120728 Bytes of space was cleaned up`

**Comment by fwartner** [comment]
Hey @luutruong!

Feel free to create and submit a PR for this! :)

**Comment by Roy-Ernst** [comment]
Just switch around old available and new available. Since you are requesting the space available the new available will be larger than the old available space.

Tested with:
```
head -c 50000000 /dev/urandom > testing.txt

oldAvailable=$(df / | tail -1 | awk '{print $4}')

rm testing.txt

newAvailable=$(df / | tail -1 | awk '{print $4}')

count=$((newAvailable - oldAvailable))

msg "$oldAvailable"
msg "$newAvailable"

bytesToHuman $count
```

TLDR;
Replace `count=$((oldAvailable - newAvailable))` with `count=$((newAvailable - oldAvailable))`

**Comment by fwartner** [comment]
Fixed now with the latest release. :)
