### ISSUE TITLE
iOS Simulator Error

### ISSUE THREAD

**Issue by Roy-Ernst** [fwartner/mac-cleanup#69]
Everytime I run the cleanup script the simulator opens briefly and outputs this error message almost instantly:

```
Cleanup iOS Simulators...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to erase contents and settings in current state: Booted
```

**Comment by fwartner** [comment]
Hey,

sorry for the delay. I personally cannot reproduce this. Would you paste the output of your terminal please?

**Comment by Roy-Ernst** [comment]
Here you go:

`royernst@Roys-MacBook-Pro ~ % cleanup
Empty the Trash on all mounted volumes and the main HDD...
Clear System Log Files...
Clear Adobe Cache Files...
Cleanup iOS Applications...
Remove iOS Device Backups...
Cleanup XCode Derived Data and Archives...
Cleanup iOS Simulators...
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to erase contents and settings in current state: Booted
Cleanup Google Chrome cache...
Cleanup composer...
Update Homebrew Recipes...
Already up-to-date.
Upgrade and remove outdated formulae
Cleanup Homebrew Cache...
Cleanup any old versions of gems
Cleanup pip cache...
Cleanup npm cache...
npm WARN using --force Recommended protections disabled.
Purge inactive memory...
Password:
Success!
6.19 KiB of space was cleaned up`

As mentioned I see the simulator app opening for a split second, then closing again, and a few seconds later it gives me that error. Hope it helps!

**Comment by Roy-Ernst** [comment]
@fwartner it seems to be fixed in the latest version (1.0.4). I used it via brew which gave me 1.0.2, I guess the version from brew is not updated (yet)?

**Comment by Roy-Ernst** [comment]
```
royernst@Roys-MacBook-Pro ~ % cleanup
Emptying the Trash on all mounted volumes and the main HDD...
Clearing System Cache Files...
Clearing System Log Files...
Clearning PhpStorm Log Files...
Clearing Adobe Cache Files...
Clearing Google Chrome Cache Files...
Cleaning up iOS Applications...
Removng iOS Device Backups...
Cleaning up XCode Derived Data and Archives...
Cleaning up iOS Simulators...
Clearing Google Drive File Stream Cache Files...
No matching processes belonging to you were found
Cleaning up composer...
Cleaning up Homebrew Cache...
/Users/royernst/Library/Caches/Homebrew/.cleaned
/Users/royernst/Library/Caches/Homebrew
Cleaning up any old versions of gems
Cleaning up npm cache...
Cleaning up DNS cache...
Password:
Purging inactive memory...
Success!
-5824 Bytes of space was cleaned up
```

This is the output with version 1.0.4. 

The phpstorm line has a typo btw: `Clear**n**ing PhpStorm Log Files...`

**Comment by Roy-Ernst** [comment]
@fwartner this one can be closed I guess. Since it's been fixed in a newer release.

(Don't forget the phpstorm message (Clear**n**ing) :P)
