### ISSUE TITLE
brew on M1 fails

### ISSUE THREAD

**Issue by jeffmurch** [fwartner/mac-cleanup#72]
==> Installing mac-cleanup from fwartner/mac-cleanup
==> Downloading {{{tarballUrl}}}

**Comment by fwartner** [comment]
Working on this.

jeffmurch ***@***.***> schrieb am Di. 15. Juni 2021 um 19:56:

**Comment by jeffmurch** [comment]
Awesome thanks!

Jeffrey Murch
Managing Director
Stirling & Young
Bedford, NH 03110
eMail: ***@***.******@***.***>
Mobile: +1 480 636 0012
https://www.sgco.com

On Jun 15, 2021, at 10:57, Florian Wartner ***@***.******@***.***>> wrote:


Working on this.

jeffmurch ***@***.***> schrieb am Di. 15. Juni 2021 um 19:56:

**Comment by fwartner** [comment]
Fixed in latest version.

**Comment by jeffmurch** [comment]
Thanks!


Jeffrey Murch
Managing Director
Stirling & Young
Bedford, NH 03110<x-apple-data-detectors://0/1>
eMail: ***@***.******@***.***>
Mobile: +14806360012
sgco.com

Sent from my iPhone 12 Pro


On Jun 23, 2021, at 08:55, Florian Wartner ***@***.***> wrote:

﻿

Fixed in latest version.
