### ISSUE TITLE
brew install problem

### ISSUE THREAD

**Issue by kikieri** [fwartner/mac-cleanup#76]
output:

Tapping fwartner/tap
Cloning into '/usr/local/Homebrew/Library/Taps/fwartner/homebrew-tap'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 116 (delta 42), reused 79 (delta 25), pack-reused 0
Receiving objects: 100% (116/116), 22.57 KiB | 2.26 MiB/s, done.
Resolving deltas: 100% (42/42), done.
Tapped 1 formula (18 files, 50.3KB).
[] ~ brew install fwartner/tap/mac-cleanup

Error: undefined method `positive?' for "c8dd7089de0798193acac6e994563bc36fa5d7a1":String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/pkg_version.rb:36:in `to_s'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/pathname.rb:350:in `initialize'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/pathname.rb:350:in `new'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/pathname.rb:350:in `+'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2301:in `versioned_prefix'
/usr/local/Homebrew/Library/Homebrew/formula.rb:582:in `prefix'
/usr/local/Homebrew/Library/Homebrew/install.rb:120:in `install_formula?'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:191:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:190:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:190:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

**Comment by fwartner** [comment]
Yep. I know and I am working on this atm.
