### ISSUE TITLE
Human bytes not displaying size correctly

### ISSUE THREAD

**Issue by Roy-Ernst** [fwartner/mac-cleanup#77]
Seems to be fixed when changing bytesToHuman() s variable from 0 to 1.

Tested with 2gb data. Displayed that 2MiB was cleaned, while it should be 2GiB.

**Comment by fwartner** [comment]
As always.. Feel free to open a PR :)

**Comment by Roy-Ernst** [comment]
See: https://github.com/fwartner/mac-cleanup/pull/78

:)

**Comment by fwartner** [comment]
Merged. :)
