### ISSUE TITLE
Feature: link to topgrade

### ISSUE THREAD

**Issue by bingalls** [fwartner/mac-cleanup#81]
Please add a link in README.md to https://github.com/r-darwish/topgrade

**Comment by fwartner** [comment]
@bingalls why should I?
There's no affiliation to this.

**Comment by bingalls** [comment]
You can add value for users, by effectively combining into a complete F/OSS periodic maintenance solution for Mac OS
* mac-cleanup removes ALL the old
* topgrade adds ALL the new

**Comment by fwartner** [comment]
Please open a PR for this and I will take a look 👀

Bruce Ingalls ***@***.***> schrieb am Sa. 17. Juli 2021 um
23:58:

**Comment by fwartner** [comment]
Won't do that.
