### ISSUE TITLE
Suggestion: Steam, Discord, and Minecraft caches

### ISSUE THREAD

**Issue by AstroOrbis** [fwartner/mac-cleanup#84]
Just a few random ideas, because Minecraft caches can sometimes take up 1.5gb+, Discord takes around 700mb+, and Steam takes a few gb sometimes :3

**Comment by fwartner** [comment]
As always, feel free to open a PR and I will look into it! :)

**Comment by AstroOrbis** [comment]
Allright, I'll get to it! ^w^

**Comment by AstroOrbis** [comment]
4 words: GitHub Copilot go brrrrrrrrrrrrrrrrrrr

**Comment by AstroOrbis** [comment]
Closed in favor of #85
